
---
title: "Write the title of the assignment"
author: "Your Name"
date: "Date"
output:
  html_document:
    highlight: pygments
    theme: spacelab
  pdf_document: default
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
# The very first time you use this R markdown file, you should install each of the packages below.
# The same goes for other packages you might decide to use
# Remember that you only need to install each R package once in R (ever -- unless you change computers).
# All you need to do whenever you need to use the package again (after restarting the R session),
# is to use the library function to call the package.
# For example, type install.packages("knitr") in the console to install the knitr package. 
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(ggplot2)
```

* * *

## Lab report

**Load data here**
```{r}
# Enter your code for loading the data here

```

### Question 1: 

[Enter your response for Question 1 here.]

```{r}
# Enter your code for question 1 here

```

### Question 2:

[Enter your response for Question 2 here.]

Here is an example of what an equation looks like using R markdown:
$$y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \ldots + \beta_p x_{ip} + \epsilon_i; \ \ \epsilon_i \overset{iid}{\sim} N(0, \sigma^2).$$
You can also write inline equations like $y = mx + c$.

```{r}
# Enter your code for question 2 here
```


### Question 3:

[Enter your response for Question 3 here.]

```{r}
# Enter your code for question 3 here
```


### Question 4:

[Enter your response for Question 4 here.]

```{r}
# Enter your code for question 4 here
```


### Question 5:

[Enter your response for Question 5 here.]

```{r}
# Enter your code for question 5 here
```


### Question 6:

[Enter your response for Question 6 here.]

```{r}
# Enter your code for question 6 here
```


* * *



